# Generated by Django 5.2.2 on 2025-06-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество продукта')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstproject.clothrs', verbose_name='Продукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstproject.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='clothes',
            field=models.ManyToManyField(through='firstproject.Pos_order', to='firstproject.clothrs', verbose_name='Товар'),
        ),
    ]
