# Generated by Django 5.2.2 on 2025-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0002_order_pos_order_order_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_firstname',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчетство'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SH', 'Вывоз из магазина'), ('CR', 'Курьер'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=2, verbose_name='Способ доставки'),
        ),
    ]
